services:
  socialapp:
    image: socialapp:latest
    build: ./app
    command: gunicorn project.wsgi:application --bind [::]:8000 --workers=3
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      app_network:
        aliases:
          - socialapp

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django
    networks:
      - app_network
  
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - socialapp
    volumes:
      - ./app/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fd00::/80"